name: Deploy spec site to AWS
on:
  push:
    branches:
    - master

env:
  AWS_DEFAULT_REGION: eu-central-1
  AWS_S3_BUCKET_NAME: wamp-proto.org
  AWS_S3_BUCKET_PATH: ''
  AWS_DISTRIBUTION_ID: E2QKV23X400P1P

jobs:
  deploy-to-aws:
    name: Deploy spec site to AWS
    runs-on: ubuntu-latest
    environment: AWS-Deployment
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'
#          architecture: 'x64'
          cache: 'pip'
      - run: export PATH=$PATH:$HOME/.local/bin
      - run: export WAMP_BUILD_ID="$(date --utc "+%Y%m%d")-$(git rev-parse --short ${GITHUB_SHA})"
      - run: pip install -r requirements.txt
      - run: pip install awscli
      - run: npm install -g grunt-cli
      - run: npm install
      - run: tox -c tox.ini -e sphinx
#      - run: npm run build # Seems to be fired from tox runner
      - run: aws s3 cp --recursive --acl public-read ./wamp-docs s3://${AWS_S3_BUCKET_NAME}/${AWS_S3_BUCKET_PATH}
      - name: Invalidate cloudfront distribution
        run: aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*"
